"""Fix migrations

Revision ID: 810dca6e617d
Revises: e7c563366262
Create Date: 2025-01-28 02:10:54.661967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810dca6e617d'
down_revision = 'e7c563366262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pizza_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_restaurant_pizzas_pizzas_id_pizzas', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_restaurant_pizzas_pizza_id_pizzas'), 'pizzas', ['pizza_id'], ['id'])
        batch_op.drop_column('pizzas_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pizzas_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_restaurant_pizzas_pizza_id_pizzas'), type_='foreignkey')
        batch_op.create_foreign_key('fk_restaurant_pizzas_pizzas_id_pizzas', 'pizzas', ['pizzas_id'], ['id'])
        batch_op.drop_column('pizza_id')

    # ### end Alembic commands ###
